#!/usr/bin/env bash

set +e

cd "$( dirname "${BASH_SOURCE[0]}" )"

export config_file="configuration"



if [ -e "$config_file" ]; then

	source $config_file
	
fi

# Ejecutamos cada modulo de la carpeta si contiene un .bash con el mismo nombre
for folder in $(ls -d */); do

	if [ -e $folder${folder%%/}.bash ]; then
		./$(echo -n $folder${folder%%/}.bash) || true
	fi

done
